Data entrypoint
Alylamppuvegaanit/discord-voice-bot-web pull request #2
Opened 2021-02-28 18:27 UTC by sjaks

[This code](https://github.com/Alylamppuvegaanit/discord-voice-bot-web/compare/data?expand=1#diff-a9259d948d9e0ef9c88b9cd5c88bd070f53ee80c503a4422b8665721fe0df282R43-R62) is vey shitty. Good algorithm needs to be coded and I haven't taken tiraka yet so maybe some one can fix this 🤔

2021-02-28 18:32 UTC, sjaks commented
Otherwise code very good, it works 😃

2021-02-28 19:15 UTC, vilukissa68 requested changes

2021-02-28 19:15 UTC, vilukissa68 commented on discord-voice-bot-web.js
> +    let combinedNewData = savedPlaylists.concat(updatedPlaylists)
This is very bad idea

2021-02-28 19:15 UTC, vilukissa68 commented on discord-voice-bot-web.js
> +    let combinedNewData = savedPlaylists.concat(updatedPlaylists)
Please make better one

2021-02-28 19:31 UTC, sjaks commented
Jaa ok

2021-03-01 16:14 UTC, vilukissa68 approved these changes
This code is lezz sitty than the last code. Good job!

2021-03-01 16:14 UTC, vilukissa68 commented on frontend/src/PlayListTable.js
> +      const tmp = songRows.concat({ title: newSongName, id: songRows.length + 1 });
Consider generating ids by random seeds

2021-03-01 16:15 UTC, sjaks commented on frontend/src/PlayListTable.js
> +      const tmp = songRows.concat({ title: newSongName, id: songRows.length + 1 });
Maybe one day yes

2021-03-01 18:42 UTC, merged